dist: bionic
language: ruby
rvm:
- 2.6.9
- 2.7.5
- 3.0.3
cache: bundler
gemfile:
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
addons:
  postgresql: '10'
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d69f1b2b4c21a45fd023
    on_success: change
    on_failure: always
    on_start: never
