language: ruby
rvm:
  - '2.3.1'
  - '2.4.1'
sudo: false
cache: bundler
before_install: gem install bundler -v 1.14.6
after_script: bundle exec codeclimate-test-reporter
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/d69f1b2b4c21a45fd023
    on_success: change
    on_failure: always
    on_start: never
